config/routes.rb
Rails.application.routes.draw do
  root to: 'root#index'

  resources :photographs do
    collection do
      get :portfolio
    end
  end

  resources :albums
end

app/models/album.rb
class Album < ApplicationRecord
  CLASSIFICATIONS = %w[collection project album]

  has_and_belongs_to_many :photographs
  belongs_to :primary_photograph, class_name: 'Photograph'

  has_many :collaborator_roles, through: :photographs
  has_many :collaborators, -> { distinct }, through: :collaborator_roles

  validates :title, presence: true
  validates :classification, presence: true, inclusion: { in: CLASSIFICATIONS }
  validate :primary_photograph_in_album

  scope :collections, -> { where(classification: 'collection') }
  scope :projects, -> { where(classification: 'project') }


  def collaborator_titles
    collaborator_roles.select(:title).distinct.pluck(:title)
  end

  private

  def primary_photograph_in_album
    unless photographs.include?(primary_photograph)
      errors[:primary_photograph] << 'must be a photograph in this album'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  has_many :roles, class_name: 'CollaboratorRole', inverse_of: :collaborator
  has_many :photographs, through: :roles

  validates :name, presence: true, uniqueness: true

  def titles_for_photograph(photograph)
    roles.for_photograph(photograph).pluck(:title)
  end
end

app/models/collaborator_role.rb
class CollaboratorRole < ApplicationRecord
  belongs_to :collaborator, inverse_of: :roles
  belongs_to :photograph, inverse_of: :collaborator_roles

  scope :for_photograph, -> (photograph) { where(photograph_id: photograph.id) }
  scope :for_collaborator, -> (collaborator) { where(collaborator_id: collaborator.id) }

  validates :title, :collaborator_id, :photograph_id, presence: true
  validates :title, uniqueness: { scope: [:collaborator_id, :photograph_id] }
end

app/models/photo_importer.rb
class PhotoImporter
  PHOTODUMP_BUCKET = 'audreypenven.photodump'

  attr_reader :client, :photographs, :bucket, :errors

  def initialize
    @client = Aws::S3::Client.new( region: ENV.fetch('AWS_REGION'),
                                  access_key_id: ENV.fetch('AWS_ACCESS_KEY_ID'),
                                  secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY'))

    @bucket = Aws::S3::Bucket.new(name: PHOTODUMP_BUCKET, client: @client)
    @photographs = []
    @errors = []
  end

  def import(options = {})
    raise 'Nothing to import' unless @bucket.objects.any?

    @bucket.objects.each do |s3_object|
      begin
        @photographs << Photograph.create!( image: URI.parse(s3_object.public_url),
                                            title: options[:title],
                                            taken_on: options[:taken_on],
                                            album_ids: options[:album_ids])
        s3_object.delete
      rescue Exception => ex
        @errors << ex
      end
    end
  end
end

app/models/photograph.rb
class Photograph < ApplicationRecord
  has_and_belongs_to_many :albums
  has_many :collaborator_roles
  has_many :collaborators, through: :collaborator_roles
  has_many :site_image_mappings

  scope :for_location, ->(location_key) {joins(:site_image_mappings).where(site_image_mappings: { location_key: location_key})}

  # Short edge measurements are based on 35mm proportions
  has_attached_file :image,
    PAPERCLIP_ATTACHMENT_OPTIONS.merge({
      styles: {
        large:      ['2000x2000>', :jpg], #short edge: 1333
        medium:     ['1000x1000>', :jpg], #short edge: 667
        small:      ['500x500>', :jpg],   #short edge: 333
        square_200: ['200x200#', :jpg],
        square_150: ['150x150#', :jpg]
      }
    })

  validates :image, attachment_presence: true
  do_not_validate_attachment_file_type :image
  # validates :taken_on, presence: true

end

app/models/site_image_mapping.rb
# This is a probably-stupid way of using photographs throughout the site
class SiteImageMapping < ApplicationRecord
  validates :location_key, presence: true
  validates :photograph_id, presence: true
  validates :photograph_id, uniqueness: {scope: :location_key}

  belongs_to :photograph
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :load_album

  def show
    @body_class = 'red-first'
    @header_image = @album.primary_photograph
  end

  private

  def load_album
    @album = Album.includes(photographs: {collaborator_roles: :collaborator}).find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :load_header_image

  def load_header_image
    possible_images = Photograph.for_location("#{controller_name}_#{action_name}-header")
    @header_image = possible_images.count > 1 ? possible_images.to_a.sample : possible_images.first
  end

  private

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      ENV['USERNAME'].present? && ENV['PASSWORD'].present? && username == ENV['USERNAME'] && password == ENV['PASSWORD']
    end
  end

end

app/controllers/photographs_controller.rb
class PhotographsController < ApplicationController
  # before_filter :authenticate, only: [:new, :create, :edit, :update]
  before_filter :load_photograph, only: [:show, :edit]

  def new
    @photograph = Photograph.new
  end

  def create
    @photograph = Photograph.new(allowed_params)
    if @photograph.save
      redirect_to @photograph
    else
      render :new
    end
  end

  def portfolio
    @body_class = 'red-first'
  end

  private

  def load_photograph
    @photograph = Photograph.find(params[:id])
    @collaborator_to_roles = @photograph.collaborator_roles.includes(:collaborator).group_by(&:collaborator)
  end

  def allowed_params
    params.require(:photograph).permit(:image)
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
    @body_class = 'red-first'

    @projects = Album.projects.order(updated_at: :desc).limit(12)
    @collections = Album.collections.order(updated_at: :desc).limit(12)
    @albums = Album.order(updated_at: :desc).limit(12)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photographs_helper.rb
module PhotographsHelper
end

app/views/albums/show.html.haml
= content_for :head do

  :javascript
    $(function() {

      $.extend($.featherlight.defaults, {
        afterContent: function(e){
          var max_height = this.$instance.height() - 40;
          var max_width = this.$instance.width() - 40;
          $('img', this.$instance).attr('style', 'max-height:' + max_height + 'px; max-width:' + max_width + 'px;');
        },
      });

      $('body').on('click tap', '.featherlight img', function() {
        $('.featherlight .meta').toggleClass('visible');
      });
    });


%section.header-photograph

%section.gallery
  .container
    %h1.red.with-underline= @album.title
    - @album.photographs.each do |photograph|
      %a.photo-link{href: "#{photograph_path(photograph)} .photograph", data: {featherlight: 'ajax' }}= image_tag(photograph.image.url(:square_150), class: 'thumbnail')


- unless @album.description.blank?
  %section.description
    .container
      = @album.description

/ # - unless @album.collaborator_titles.empty?

app/views/layouts/application.html.haml
!!! HTML

%html
  %head
    %title Audrey Penven
    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = yield :head
    - if @header_image
      :css
        @media (max-width: 333px) {
          .header-photograph {
            background-image: url("#{@header_image.image.url(:small)}");
          }
        }
        @media (max-width: 667px) {
          .header-photograph {
            background-image: url("#{@header_image.image.url(:medium)}");
          }
        }
        @media (min-width: 668px) {
          .header-photograph {
            background-image: url("#{@header_image.image.url(:large)}");
          }
        }

  %body{class: "#{controller_name}-#{action_name} #{@body_class}"}
    = render 'shared/header'
    .wrapper
      .page-content= yield
      = render 'shared/footer'

app/views/photographs/new.html.haml
= form_for @photograph do |f|
  %div
    = f.file_field :image
  %div
    = f.label :taken_on
    = f.date_select :taken_on
  %div
    = f.label :title
    = f.text_field :title
  = f.submit 'Upload'

app/views/photographs/portfolio.html.haml
%section
  .container
    %h1.black.with-underline
      Photography Portfolio

%section.album-background-image.dancing-with-invisible-light

%section
  .container
    %a{href: 'dancing-with-invisible-light/'}
      %h2 Dancing With Invisible Light

%section.album-background-image.six

%section
  .container
    %a{href: 'six/'}
      %h2 Six

%section.album-background-image.portraits

%section
  .container
    %a{href: 'portraits/'}
      %h2 Portraits

%section.album-background-image.music

%section
  .container
    %a{href: 'music/'}
      %h2 Music

%section.album-background-image.hubba-hubba-revue

%section
  .container
    %a{href: 'hubba-hubba-revue'}
      %h2 Hubba Hubba Revue

app/views/photographs/show.html.haml
.photograph
  = image_tag @photograph.image.url(:medium)
  .meta
    - if @photograph.title
      %h4= @photograph.title
    - if @collaborator_to_roles
      %h5.collaborators Collaborators
      %ul
        - @collaborator_to_roles.each do |collaborator, roles|
          %li
            = "#{roles.map(&:title).join(', ')}: "
            - if collaborator.url
              = link_to collaborator.name, collaborator.url, target: :_blank
            - else
              = collaborator.name

app/views/root/index.html.haml
%section.site-title.header-photograph
  .title
    =image_tag('logo_large.png', alt: 'Audrey Penven', class: 'site-logo')

%section.portfolio
  .photo-projects
    %h2.red.with-underline Projects
    %div
      - @projects.each do |album|
        .project-album-link.album-link
          = image_tag(album.primary_photograph.image.url(:square_150), alt: "@album.title")
          = link_to album_path(album) do
            %h5.album-title= album.title

  .photo-collections
    %h2.red.with-underline Collections
    %div
      - @collections.each do |album|
        .collection-album-link.album-link
          = image_tag(album.primary_photograph.image.url(:square_150), alt: "@album.title")
          = link_to album_path(album) do
            %h5.album-title= album.title
%section.photo-stream
  %div
    %h2.black.with-underline Full Photo Archive
    %div
      - @albums.each do |album|
        .stream-album-link.album-link
          = image_tag(album.primary_photograph.image.url(:square_150), alt: "@album.title")
          = link_to album_path(album) do
            %h5.album-title= album.title

%section.contact
  %div
    .image-with-caption.pull-left.bio-photo
      = image_tag('me-by-nadya-400x400.jpg', class: 'black-border')
      %p
        photo by
        = link_to 'Nadya Lev', 'http://www.nadyalevphoto.com/'

    %h2.red Me, elsewhere
    %table.find-elsewhere
      %tr
        %td
          = fa_icon 'envelope fw'
          email
        %td
          %a{href: 'mailto:audrey@audreypenven.net'}
            audrey@audreypenven.net
      %tr
        %td
          = fa_icon 'twitter fw'
          twitter
        %td
          %a{href: 'http://www.twitter.com/yerdua'}
            @yerdua
      %tr
        %td
          = fa_icon 'flickr fw'
          flickr
        %td
          %a{href: 'https://www.flickr.com/photos/audreypenven/'}
            flickr.com/photos/audreypenven
      %tr
        %td
          = fa_icon 'instagram fw'
          instagram
        %td
          %a{href: 'http://instagram.com/y3rdua'}
            @y3rdua
      %tr
        %td
          = fa_icon 'github fw'
          github
        %td
          %a{href: 'https://github.com/yerdua'}
            github.com/yerdua

app/views/shared/_footer.html.haml
%footer.site-footer
  %h2
    = Date.today.year
    Audrey Penven

app/views/shared/_header.html.haml
%header.site-header
  %a{href: root_path}
    = image_tag('symbol_sml.png', class: 'logo', alt: 'Audrey Penven')
  %nav.site-nav
    %ul
      %li
        = link_to 'Photography Portfolio', photographs_path

      %li
        = link_to 'About', '#'